"use client";

import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { ArrowPathIcon, CheckBadgeIcon, MapPinIcon } from "@heroicons/react/24/outline";
import { Button } from "@/components/ui/Button";

interface Farm { id: string; name: string; contactPerson: string; phone: string; location: string; region: string; certification?: string | null; produceItems: Array<{ name: string }>; }
export default function AdminFarms() {
  const [farms, setFarms] = useState<Farm[]>([]); const [form, setForm] = useState({ name: "", contactPerson: "", phone: "", location: "", certification: "" }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => { setLoading(true); const res = await fetch("/api/admin/farms", { cache: "no-store" }); const data = await res.json(); if (res.ok) setFarms(data); setLoading(false); };
  useEffect(() => { load(); }, []);
  const addFarm = async (e: FormEvent) => { e.preventDefault(); setSaving(true); setError(""); const res = await fetch("/api/admin/farms", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) setError(data.error || "Failed"); else { setForm({ name: "", contactPerson: "", phone: "", location: "", certification: "" }); load(); } setSaving(false); };
  if (loading) return <p className="text-sm text-muted">Loading farms…</p>;
  return <div className="space-y-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Supply network</p><h1 className="mt-2 font-display text-4xl font-semibold text-primary-deep">Partner farms</h1><p className="mt-2 text-sm text-muted">The growers behind each FreshCrate harvest.</p></div><Button variant="outline" size="sm" onClick={load}><ArrowPathIcon className="mr-2 size-4" aria-hidden="true" /> Refresh</Button></header><section className="rounded-2xl border border-line bg-surface p-5 sm:p-6"><div className="mb-5"><p className="eyebrow">Add a partner</p><h2 className="mt-2 font-display text-2xl font-semibold text-ink">Register a farm</h2></div>{error && <p role="alert" className="mb-4 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}<form onSubmit={addFarm} className="grid gap-3 sm:grid-cols-2"><input className="input" placeholder="Farm name" required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><input className="input" placeholder="Contact person" required value={form.contactPerson} onChange={(e) => setForm({ ...form, contactPerson: e.target.value })} /><input className="input" placeholder="Phone (+233...)" required value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input className="input" placeholder="Location / community" required value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })} /><input className="input" placeholder="Certification (optional)" value={form.certification} onChange={(e) => setForm({ ...form, certification: e.target.value })} /><Button type="submit" disabled={saving}>{saving ? "Saving…" : "Add farm"}</Button></form></section><section className="grid gap-3 sm:grid-cols-2">{farms.map((farm) => <article key={farm.id} className="rounded-2xl border border-line bg-surface p-5 transition-shadow hover:shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="font-display text-2xl font-semibold text-ink">{farm.name}</h2>{farm.certification && <CheckBadgeIcon className="size-5 text-primary" aria-label={farm.certification} />}</div><p className="mt-2 text-sm text-muted">{farm.contactPerson} · {farm.phone}</p><p className="mt-3 flex items-center gap-2 text-sm text-muted"><MapPinIcon className="size-4 text-primary" aria-hidden="true" />{farm.location} · {farm.region}</p>{farm.certification && <p className="mt-3 text-xs font-semibold uppercase tracking-[0.1em] text-primary">{farm.certification}</p>}<p className="mt-4 border-t border-line pt-3 text-xs text-muted">{farm.produceItems.length} produce item(s) sourced</p></article>)}{farms.length === 0 && <p className="text-sm text-muted">No farms yet.</p>}</section></div>;
}
